### PR TITLE
Update prebuild to v13

### PR DESCRIPTION
**Pull request by orgads**
This updates node-gyp dependency, and should fix the build on macos.

### CODE REVIEW

**Comment by baptisteArno** [comment]
@orgads @laverdet Why was that removed? It makes the package incompatible with Vercel deployment. (#477)

**Comment by orgads** [comment]
@baptisteArno Why was *what* removed? Suppose you mean `pip install distutils`, it was removed from github actions because the updated `prebuild` uses a newer `node-gyp`, which no longer needs this workaround. How is this related to Vercel?

**Comment by baptisteArno** [comment]
> Suppose you mean pip install distutils

Yes sorry 🙏

When upgrading the package, the build on Vercel fails with error: `No module named 'distutils'`. But if I upgrade, It is supposed to use the updated prebuild you mention, right? Then I'm not sure what's wrong here 🤔

**Comment by orgads** [comment]
Then I guess you need to install `distutils` on vercel?

**Comment by laverdet** [comment]
@baptisteArno is just confused. The binaries for v4.8.0 were not uploaded because of a compilation issue. So if you rely on prebuilt binaries then you can't use that point release. GitHub actions are not invoked during npm install, my friend.

**Pull request merged**
