### PR TITLE
Add typescript definition

### PR DESCRIPTION
**Pull request by rs**

### CODE REVIEW

**Comment by laverdet** [comment]
Should this be `index.d.ts` or `isolated-vm.d.ts`? I renamed `index.js` to `isolated-vm.js` yesterday so maybe this needs to be renamed too. No need to update the pull request I can rename it on my end but I wanted to check because I don't use typescript.

**Comment by rs** [comment]
I’m not sure, I’m kind of noob with Typescript.

**Comment by laverdet** [comment]
I think it's supposed to match the source file, so it should probably be `isolated-vm.d.ts`. Could you please confirm you still get annotations with the latest master and your .d.ts named isolated-vm.d.ts. If so I'll go ahead and merge this with the renamed file.

**Comment by rs** [comment]
I can confirm that if it is renamed to `isolated-vm.d.ts`, typescript can not find it. Apparently, you need to declare a `types` key in the `package.json` file if you want to use a different name.

**Comment by laverdet** [comment]
Merged squashed via a0b8fe01c8cf44f78a8c47c68293274ddf218d08. I converted the spaces to tabs as well because I'm a monster.

**Pull request closed without merging**
