### PR TITLE
Support prebuild

### LINKED ISSUE #201: [feature] Provide precompiled libraries
Would it be possible to provide precompiled node bindings? Compiling on Linux is easy, but on Windows it's quite a mess.

### LINKED ISSUE #297: Publishing Prebuild binaries
Hi @laverdet !

Thanks again for this great library. I am wondering if it's possible to publish prebuilt binaries that are similar to https://github.com/sass/node-sass/releases for easier installation for different platforms/arch?

I am happy to help if any work need to be done. I saw that currently this repo is using travis to build. And the pricing for the free tier  on travis doesn't seem to be friendly for the prebuild binaries. 

If publishing binaries becomes an option, this repo may need to switch to something like `github action` or `appveyor`

### PR DESCRIPTION
**Pull request by orgads**
Simplifies distribution of pre-built binaries.

Fixes #201
Fixes #297

### CODE REVIEW

**Comment by orgads** [comment]
Sample release: https://github.com/orgads/isolated-vm/releases

Until this is accepted, my release can be installed using:
```bash
npm install isolated-vm-prebuilt
```

**Comment by orgads** [comment]
In order to get it working, you need to create a token here: https://github.com/settings/personal-access-tokens/new

In Repository access, choose the `isolated-vm` repository, expand Repository permissions -> Contents -> Read and write.

Copy the generated token, then create a secret in the repository here: https://github.com/laverdet/isolated-vm/settings/secrets/actions/new
name: `UPLOAD_TOKEN`
Secret: `<the copied value>`

And you're all set! When you create a release, binary artifacts will be created automatically.

This can be also enabled for tags if you prefer not to manually create Github releases.

**Comment by alumni** [comment]
@laverdet can you please consider this? The only alternative, `vm2` has been discontinued due to security issues.

**Comment by laverdet** [comment]
Thanks for the contribution. I had a really bad time with precompiled binaries while supporting node-fibers so I resolved not to support them in this project. Maybe prebuild will be easier though.

**Pull request merged**
